[package]
name = "rust_testing"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.7.3"
